// ============================================
// PRISMA DATABASE ENUMS
// These are defined in schema.prisma and generated by Prisma
// Re-exported here for convenience
// ============================================

/**
 * Role - Defines the user roles in the system
 */
export enum Role {
  ADMIN = "ADMIN",
  RECRUITER = "RECRUITER",
  MEMBER = "MEMBER",
}

/**
 * ExperienceLevel - Represents the experience level of a user or job requirement
 */
export enum ExperienceLevel {
  INTERN = "INTERN",
  ENTRY = "ENTRY",
  MID = "MID",
  SENIOR = "SENIOR",
  STAFF = "STAFF",
  PRINCIPAL = "PRINCIPAL",
  EXECUTIVE = "EXECUTIVE",
}

/**
 * ReferralStatus - Tracks the lifecycle of a referral
 */
export enum ReferralStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  INTERVIEWING = "INTERVIEWING",
  OFFERED = "OFFERED",
  HIRED = "HIRED",
  REJECTED = "REJECTED",
  WITHDRAWN = "WITHDRAWN",
}

/**
 * RelationType - Defines the relationship between the referrer and the candidate
 */
export enum RelationType {
  FRIEND = "FRIEND",
  EX_COLLEAGUE = "EX_COLLEAGUE",
  RELATIVE = "RELATIVE",
  CLASSMATE = "CLASSMATE",
  MENTOR = "MENTOR",
  MENTEE = "MENTEE",
  OTHER = "OTHER",
}

/**
 * EventType - Represents the types of events tracked for analytics
 */
export enum EventType {
  // Job-related events
  JOB_VIEWED = "JOB_VIEWED",
  JOB_CREATED = "JOB_CREATED",
  JOB_UPDATED = "JOB_UPDATED",
  JOB_CLOSED = "JOB_CLOSED",
  JOB_CLOSING_REMINDER = "JOB_CLOSING_REMINDER",

  // Nudge-related events
  NUDGES_SHOWN = "NUDGES_SHOWN",
  NUDGE_CLICKED = "NUDGE_CLICKED",
  NUDGE_DISMISSED = "NUDGE_DISMISSED",

  // Message-related events
  MESSAGE_COPIED = "MESSAGE_COPIED",
  MESSAGE_GENERATED = "MESSAGE_GENERATED",

  // Referral-related events
  REFERRAL_STARTED = "REFERRAL_STARTED",
  REFERRAL_SUBMITTED = "REFERRAL_SUBMITTED",
  REFERRAL_STATUS_CHANGED = "REFERRAL_STATUS_CHANGED",
  REFERRAL_WITHDRAWN = "REFERRAL_WITHDRAWN",

  // Profile-related events
  PROFILE_UPDATED = "PROFILE_UPDATED",
  PROFILE_VIEWED = "PROFILE_VIEWED",
  PREFERENCES_UPDATED = "PREFERENCES_UPDATED",

  // Auth-related events
  LOGIN = "LOGIN",
  SIGNUP = "SIGNUP",
  LOGOUT = "LOGOUT",
  PASSWORD_RESET = "PASSWORD_RESET",

  // Search-related events
  SEARCH_PERFORMED = "SEARCH_PERFORMED",
  FILTER_APPLIED = "FILTER_APPLIED",
}

// ============================================
// JOB PARSER ENUMS
// Used in job.parser.ts for parsing job descriptions
// ============================================

/**
 * RemoteType - Defines the remote work type for a job
 */
export enum RemoteType {
  REMOTE = "remote",
  HYBRID = "hybrid",
  ONSITE = "onsite",
  UNKNOWN = "unknown",
}

/**
 * EmploymentType - Defines the employment type for a job
 */
export enum EmploymentType {
  FULL_TIME = "full-time",
  PART_TIME = "part-time",
  CONTRACT = "contract",
  INTERNSHIP = "internship",
  FREELANCE = "freelance",
  TEMPORARY = "temporary",
  UNKNOWN = "unknown",
}

/**
 * CompanyType - Defines the type of company
 */
export enum CompanyType {
  STARTUP = "startup",
  SCALEUP = "scaleup",
  ENTERPRISE = "enterprise",
  AGENCY = "agency",
  NONPROFIT = "nonprofit",
  GOVERNMENT = "government",
  UNKNOWN = "unknown",
}

/**
 * JobDomain - Defines the industry domain of a job
 */
export enum JobDomain {
  FINTECH = "fintech",
  HEALTHTECH = "healthtech",
  EDTECH = "edtech",
  ECOMMERCE = "ecommerce",
  SAAS = "saas",
  GAMING = "gaming",
  MEDIA = "media",
  SECURITY = "security",
  AI = "ai",
  LOGISTICS = "logistics",
  REAL_ESTATE = "real_estate",
  TRAVEL = "travel",
  FOOD_DELIVERY = "food_delivery",
  SOCIAL = "social",
  DEVTOOLS = "devtools",
  BLOCKCHAIN = "blockchain",
  IOT = "iot",
  AUTOMOTIVE = "automotive",
  AEROSPACE = "aerospace",
  ENERGY = "energy",
  GENERAL = "general",
}

/**
 * SkillCategory - Categorizes skills for better organization
 */
export enum SkillCategory {
  PROGRAMMING_LANGUAGE = "programming_language",
  FRONTEND = "frontend",
  BACKEND = "backend",
  DATABASE = "database",
  CLOUD = "cloud",
  DEVOPS = "devops",
  MOBILE = "mobile",
  DATA_SCIENCE = "data_science",
  MACHINE_LEARNING = "machine_learning",
  SECURITY = "security",
  TESTING = "testing",
  SOFT_SKILL = "soft_skill",
  MANAGEMENT = "management",
  DESIGN = "design",
  OTHER = "other",
}

/**
 * SeniorityIndicator - Indicates seniority-related responsibilities
 */
export enum SeniorityIndicator {
  TEAM_LEAD = "team_lead",
  TECH_LEAD = "tech_lead",
  MANAGEMENT = "management",
  MENTORSHIP = "mentorship",
  ARCHITECTURE = "architecture",
  FOUNDING_TEAM = "founding_team",
  IC_TRACK = "ic_track",
  PLAYER_COACH = "player_coach",
  PEOPLE_MANAGEMENT = "people_management",
  STRATEGIC_PLANNING = "strategic_planning",
}

// ============================================
// NUDGE ENGINE ENUMS
// Used in nudge.engine.ts for generating referral nudges
// ============================================

/**
 * NudgeCategory - Categorizes nudge suggestions
 */
export enum NudgeCategory {
  SKILL_MATCH = "skill_match",
  COMPANY_MATCH = "company_match",
  DOMAIN_MATCH = "domain_match",
  EXPERIENCE_MATCH = "experience_match",
  LOCATION_MATCH = "location_match",
  EDUCATION_MATCH = "education_match",
  RELATIONSHIP_BASED = "relationship_based",
  GENERAL = "general",
}

/**
 * NudgePriority - Defines the priority level of a nudge
 */
export enum NudgePriority {
  HIGH = "high",
  MEDIUM = "medium",
  LOW = "low",
}

/**
 * NudgeMatchStrength - Indicates how strong a nudge match is
 */
export enum NudgeMatchStrength {
  STRONG = "strong",
  MODERATE = "moderate",
  WEAK = "weak",
}

// ============================================
// REFERRAL SERVICE ENUMS
// Used in referrals.service.ts
// ============================================

/**
 * ReferralOutcome - Final outcome of a referral
 */
export enum ReferralOutcome {
  PENDING = "pending",
  HIRED = "hired",
  REJECTED = "rejected",
  WITHDRAWN = "withdrawn",
  EXPIRED = "expired",
}

/**
 * ReferralStage - Stages in the referral pipeline
 */
export enum ReferralStage {
  INITIAL_REVIEW = "initial_review",
  PHONE_SCREEN = "phone_screen",
  TECHNICAL_INTERVIEW = "technical_interview",
  ONSITE_INTERVIEW = "onsite_interview",
  FINAL_ROUND = "final_round",
  OFFER_STAGE = "offer_stage",
  CLOSED = "closed",
}

// ============================================
// AUTH ENUMS
// Used in auth.ts
// ============================================

/**
 * AuthErrorCode - Error codes for authentication failures
 */
export enum AuthErrorCode {
  INVALID_CREDENTIALS = "invalid_credentials",
  USER_NOT_FOUND = "user_not_found",
  USER_DISABLED = "user_disabled",
  EMAIL_TAKEN = "email_taken",
  WEAK_PASSWORD = "weak_password",
  INVALID_TOKEN = "invalid_token",
  TOKEN_EXPIRED = "token_expired",
  UNAUTHORIZED = "unauthorized",
  FORBIDDEN = "forbidden",
  SESSION_EXPIRED = "session_expired",
}

/**
 * TokenType - Types of authentication tokens
 */
export enum TokenType {
  ACCESS = "access",
  REFRESH = "refresh",
  RESET_PASSWORD = "reset_password",
  EMAIL_VERIFICATION = "email_verification",
}

// ============================================
// CRON JOB ENUMS
// Used in cron jobs
// ============================================

/**
 * CronJobName - Names of scheduled cron jobs
 */
export enum CronJobName {
  REFRESH_MEMBER_PROFILES = "refresh_member_profiles",
  JOB_CLOSING_REMINDERS = "job_closing_reminders",
  CLEANUP_OLD_EVENTS = "cleanup_old_events",
  REFRESH_JOB_TAGS = "refresh_job_tags",
  SEND_WEEKLY_DIGEST = "send_weekly_digest",
}

/**
 * CronJobStatus - Status of a cron job execution
 */
export enum CronJobStatus {
  STARTED = "started",
  RUNNING = "running",
  COMPLETED = "completed",
  FAILED = "failed",
  SKIPPED = "skipped",
}

// ============================================
// MESSAGE TEMPLATE ENUMS
// Used for message generation
// ============================================

/**
 * MessageTemplateType - Types of message templates
 */
export enum MessageTemplateType {
  REFERRAL_REQUEST = "referral_request",
  INTRODUCTION = "introduction",
  FOLLOW_UP = "follow_up",
  THANK_YOU = "thank_you",
  JOB_SHARE = "job_share",
  REMINDER = "reminder",
}

/**
 * MessageTone - Tone of the message
 */
export enum MessageTone {
  FORMAL = "formal",
  CASUAL = "casual",
  FRIENDLY = "friendly",
  PROFESSIONAL = "professional",
}

// ============================================
// API RESPONSE ENUMS
// Used for standardized API responses
// ============================================

/**
 * ApiErrorCode - Standardized API error codes
 */
export enum ApiErrorCode {
  // Client errors (4xx)
  BAD_REQUEST = "bad_request",
  UNAUTHORIZED = "unauthorized",
  FORBIDDEN = "forbidden",
  NOT_FOUND = "not_found",
  CONFLICT = "conflict",
  VALIDATION_ERROR = "validation_error",
  RATE_LIMITED = "rate_limited",

  // Server errors (5xx)
  INTERNAL_ERROR = "internal_error",
  SERVICE_UNAVAILABLE = "service_unavailable",
  DATABASE_ERROR = "database_error",
  EXTERNAL_SERVICE_ERROR = "external_service_error",
}

/**
 * SortOrder - Sort order for queries
 */
export enum SortOrder {
  ASC = "asc",
  DESC = "desc",
}

/**
 * FilterOperator - Operators for filtering
 */
export enum FilterOperator {
  EQUALS = "equals",
  NOT_EQUALS = "not_equals",
  CONTAINS = "contains",
  STARTS_WITH = "starts_with",
  ENDS_WITH = "ends_with",
  GREATER_THAN = "greater_than",
  LESS_THAN = "less_than",
  GREATER_THAN_OR_EQUAL = "greater_than_or_equal",
  LESS_THAN_OR_EQUAL = "less_than_or_equal",
  IN = "in",
  NOT_IN = "not_in",
  BETWEEN = "between",
}

// ============================================
// NOTIFICATION ENUMS
// For future notification system
// ============================================

/**
 * NotificationType - Types of notifications
 */
export enum NotificationType {
  REFERRAL_RECEIVED = "referral_received",
  REFERRAL_STATUS_UPDATED = "referral_status_updated",
  JOB_MATCH = "job_match",
  JOB_CLOSING_SOON = "job_closing_soon",
  PROFILE_INCOMPLETE = "profile_incomplete",
  WEEKLY_DIGEST = "weekly_digest",
  SYSTEM_ANNOUNCEMENT = "system_announcement",
}

/**
 * NotificationChannel - Channels for sending notifications
 */
export enum NotificationChannel {
  EMAIL = "email",
  IN_APP = "in_app",
  PUSH = "push",
  SMS = "sms",
}

/**
 * NotificationStatus - Status of a notification
 */
export enum NotificationStatus {
  PENDING = "pending",
  SENT = "sent",
  DELIVERED = "delivered",
  READ = "read",
  FAILED = "failed",
}

// ============================================
// ANALYTICS ENUMS
// For analytics and reporting
// ============================================

/**
 * AnalyticsPeriod - Time periods for analytics
 */
export enum AnalyticsPeriod {
  TODAY = "today",
  YESTERDAY = "yesterday",
  LAST_7_DAYS = "last_7_days",
  LAST_30_DAYS = "last_30_days",
  LAST_90_DAYS = "last_90_days",
  THIS_MONTH = "this_month",
  LAST_MONTH = "last_month",
  THIS_QUARTER = "this_quarter",
  THIS_YEAR = "this_year",
  ALL_TIME = "all_time",
  CUSTOM = "custom",
}

/**
 * MetricType - Types of metrics tracked
 */
export enum MetricType {
  COUNT = "count",
  SUM = "sum",
  AVERAGE = "average",
  PERCENTAGE = "percentage",
  RATE = "rate",
}

// ============================================
// EXPORT ALL ENUMS AS A NAMESPACE
// For convenient imports
// ============================================

export const Enums = {
  // Prisma enums
  Role,
  ExperienceLevel,
  ReferralStatus,
  RelationType,
  EventType,

  // Job parser enums
  RemoteType,
  EmploymentType,
  CompanyType,
  JobDomain,
  SkillCategory,
  SeniorityIndicator,

  // Nudge engine enums
  NudgeCategory,
  NudgePriority,
  NudgeMatchStrength,

  // Referral enums
  ReferralOutcome,
  ReferralStage,

  // Auth enums
  AuthErrorCode,
  TokenType,

  // Cron job enums
  CronJobName,
  CronJobStatus,

  // Message template enums
  MessageTemplateType,
  MessageTone,

  // API enums
  ApiErrorCode,
  SortOrder,
  FilterOperator,

  // Notification enums
  NotificationType,
  NotificationChannel,
  NotificationStatus,

  // Analytics enums
  AnalyticsPeriod,
  MetricType,
};

export default Enums;